### ISSUE TITLE
Loading issue of JS component on multiple pages

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/mincong-h.github.io#51]
## Description

* Archive pages disappeared (https://mincong.io/en/archive/) -- only tags are shown
* Side bar for content navigation is not shown anymore.
* Search bar is not working

Thanks @omegacoustic for notifying me

## Troubleshooting

It seems that two resources cannot be loaded:

recommendation.js:
```
recommendations.js:35 Uncaught ReferenceError: $LIVERAMP is not defined
    at recommendations.js:35:1
(anonymous) @ recommendations.js:35
```

jquery:

```
(index):248 GET https://cdn.bootcss.com/jquery/3.1.1/jquery.min.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by omegacoustic** [comment]
it works again!

**Comment by mincong-h** [comment]
Thanks for your help @omegacoustic . Although the resources loaded again but I decided to host these resources directly in the blog in github so that I can avoid the same situation from happening again. I also took this opportunity to upgrade the jQuery version.
